export const PROFESSIONS = [
  { name: "Accordeur de pianos", category: "CREATIF" },
  { name: "Ambulancier", category: "SANTE" },
  { name: "Archetier", category: "ARTISAN" },
  { name: "Auto-école", category: "SERVICES" },
  { name: "Bijouterie", category: "CREATIF" },
  { name: "Bottier", category: "ARTISAN" },
  { name: "Boulangerie", category: "FOOD" },
  { name: "Boucherie", category: "FOOD" },
  { name: "Brasseur", category: "FOOD" },
  { name: "Café / Bar", category: "FOOD" },
  { name: "Canalisateur", category: "ARTISAN" },
  { name: "Carreleur-mosaïste", category: "ARTISAN" },
  { name: "Carrossier", category: "ARTISAN" },
  { name: "Charcutier", category: "FOOD" },
  { name: "Chaudronnier", category: "ARTISAN" },
  { name: "Chauffagiste", category: "ARTISAN" },
  { name: "Chauffeur de taxi", category: "SERVICES" },
  { name: "Charpente", category: "ARTISAN" },
  { name: "Charpentier", category: "ARTISAN" },
  { name: "Chocolatier-confiseur", category: "FOOD" },
  { name: "Coiffeur", category: "CREATIF" },
  { name: "Collectionneur", category: "CREATIF" },
  { name: "Cordonnier", category: "ARTISAN" },
  { name: "Couturier", category: "CREATIF" },
  { name: "Couverture", category: "ARTISAN" },
  { name: "Couvreur", category: "ARTISAN" },
  { name: "Crêpier", category: "FOOD" },
  { name: "Déménageur", category: "SERVICES" },
  { name: "Ebéniste", category: "ARTISAN" },
  { name: "Électricité", category: "ARTISAN" },
  { name: "École de musique", category: "CREATIF" },
  { name: "École de danse", category: "CREATIF" },
  { name: "Electricien", category: "ARTISAN" },
  { name: "Encadreur", category: "ARTISAN" },
  { name: "Épicerie", category: "FOOD" },
  { name: "Esthéticien cosméticien", category: "SANTE" },
  { name: "Façonnier", category: "ARTISAN" },
  { name: "Facteur d'instruments de musique", category: "ARTISAN" },
  { name: "Ferronnier", category: "ARTISAN" },
  { name: "Fleuriste", category: "CREATIF" },
  { name: "Fondeur", category: "ARTISAN" },
  { name: "Fourreur", category: "CREATIF" },
  { name: "Garage automobile", category: "SERVICES" },
  { name: "Glacier", category: "FOOD" },
  { name: "Graveur sur pierre", category: "ARTISAN" },
  { name: "Horloger", category: "ARTISAN" },
  { name: "Immobilier", category: "SERVICES" },
  { name: "Joaillier", category: "CREATIF" },
  { name: "Kinésithérapie", category: "SANTE" },
  { name: "Lapidaire", category: "ARTISAN" },
  { name: "Librairie", category: "CREATIF" },
  { name: "Maçonnerie", category: "ARTISAN" },
  { name: "Maréchal-ferrant", category: "ARTISAN" },
  { name: "Maroquinier", category: "ARTISAN" },
  { name: "Marqueteur", category: "ARTISAN" },
  { name: "Mécanicien automobile", category: "SERVICES" },
  { name: "Mécanicien Motocycles", category: "SERVICES" },
  { name: "Mécanicien de maintenance des matériels d'espaces verts", category: "SERVICES" },
  { name: "Menuiserie", category: "ARTISAN" },
  { name: "Métallerie", category: "ARTISAN" },
  { name: "Modéliste textile", category: "CREATIF" },
  { name: "Modiste", category: "CREATIF" },
  { name: "Opérateur en productique mécanique", category: "SERVICES" },
  { name: "Optique", category: "SANTE" },
  { name: "Orfèvre", category: "ARTISAN" },
  { name: "Orthoprothésiste", category: "SANTE" },
  { name: "Pâtisserie", category: "FOOD" },
  { name: "Peintre en bâtiment", category: "ARTISAN" },
  { name: "Peintre en décor", category: "CREATIF" },
  { name: "Pharmacie", category: "SANTE" },
  { name: "Photographe", category: "CREATIF" },
  { name: "Plombier", category: "ARTISAN" },
  { name: "Podo-orthésiste", category: "SANTE" },
  { name: "Podologue", category: "SANTE" },
  { name: "Poissonnier", category: "FOOD" },
  { name: "Potier-céramiste", category: "ARTISAN" },
  { name: "Pressing", category: "SERVICES" },
  { name: "Prothésiste dentaire", category: "SANTE" },
  { name: "Ramoneur", category: "ARTISAN" },
  { name: "Restaurant", category: "FOOD" },
  { name: "Sellier", category: "ARTISAN" },
  { name: "Sérigraphe", category: "CREATIF" },
  { name: "Sertisseur", category: "ARTISAN" },
  { name: "Serrurerie", category: "ARTISAN" },
  { name: "Tailleur", category: "CREATIF" },
  { name: "Tapissier", category: "ARTISAN" },
  { name: "Taxi / VTC", category: "SERVICES" },
  { name: "Tonnelier", category: "ARTISAN" },
  { name: "Traiteur", category: "FOOD" },
  { name: "Verrier", category: "ARTISAN" },
  { name: "Vétérinaire", category: "SANTE" },
  { name: "Vitrailliste", category: "ARTISAN" },
  { name: "Autre", category: "SERVICES" }
];
